In [16]:
from torch import cos, sin, Tensor
from typing import List, Tuple
import torch

# Simulator 

In this document I will produce a prototype stochastic simulator for the path of a marine vessel. The simulator is a toy, based neither on real physics or real data. It does, however, provide a method to generate fake data upon which I will build a proof-of-principle probabilistic trajectory predictor.

## Rationale

For a real ship, the relevant variables are complicated, depending on everything from hull form to water depth. 

For my simulator I will only consider rudder angle and velocity. These will be chosen stochastically, with some small assumptions (velocity will tend positive, rudder angle will tend straight). Every ship will be initialised in the same position and with the same orientation. This latter point isn't too ridiculous, since it just amounts to centering the coordinate system over the boat at initialisiation, and hence doesn't actually result in a loss of generality if we assume that the trajectory is invariant to the initial position. This won't always be the case with real ships, which for example, are unlikely to sail into land, but can be a good approximation in some restrictive cases, such as at deep sea.

In [26]:
def arc_trace_centered(velocity: Tensor, 
              rudder_angle: Tensor, 
              time_steps: int = 10,
              record_resolution: int = 1) -> List[Tensor]:
    """A function for tracing an arc-segment of a ship's trajectory.
    Toy model which simply assumes that the arc radius depends purely on rudder angle.
    Centers the coordinate frame on the ship, and rotates it so the ships starts
    with a vertical orientation.
    
    Args:
        velocity (Tensor): the ship's velocity for the present timestep.
        rudder_angle (Tensor): the rudder angle relative to the ship's orientation.
        time_step (float): amount of time over which to integrate trajectory.
        record_resolution (float): the time resolution with which the position of ship is recorded.
    """
    assert torch.abs(torch.tensor(rudder_angle)) <= torch.pi/4, "abs(rudder_angle) must be <= pi/4"
    assert time_steps%record_resolution==0, "record_resolution must be a factor of time_steps"
    
    # assume a 100 unit arc_radius at 45 degree rudder
    arc_radius = 100/torch.tan(rudder_angle)
    total_steps = time_steps//record_resolution
    position_deltas = []
    for i in range(total_steps):
        distance_moved = velocity*record_resolution*(i+1)
        print(distance_moved)
        subtended_angle = distance_moved/arc_radius
        new_position_delta = distance_moved*torch.tensor([sin(subtended_angle), cos(subtended_angle)])
        position_deltas.append(new_position_delta)

    return position_deltas    

In [27]:
arc_trace_centered(torch.tensor(7),torch.tensor(0),100)

/tmp/ipykernel_1459/954280534.py:16: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  assert torch.abs(torch.tensor(rudder_angle)) <= torch.pi/4, "abs(rudder_angle) must be <= pi/4"


tensor(20)
tensor(40)
tensor(60)
tensor(80)
tensor(100)
tensor(120)
tensor(140)
tensor(160)
tensor(180)
tensor(200)
tensor(220)
tensor(240)
tensor(260)
tensor(280)
tensor(300)
tensor(320)
tensor(340)
tensor(360)
tensor(380)
tensor(400)
tensor(420)
tensor(440)
tensor(460)
tensor(480)
tensor(500)
tensor(520)
tensor(540)
tensor(560)
tensor(580)
tensor(600)
tensor(620)
tensor(640)
tensor(660)
tensor(680)
tensor(700)
tensor(720)
tensor(740)
tensor(760)
tensor(780)
tensor(800)
tensor(820)
tensor(840)
tensor(860)
tensor(880)
tensor(900)
tensor(920)
tensor(940)
tensor(960)
tensor(980)
tensor(1000)
tensor(1020)
tensor(1040)
tensor(1060)
tensor(1080)
tensor(1100)
tensor(1120)
tensor(1140)
tensor(1160)
tensor(1180)
tensor(1200)
tensor(1220)
tensor(1240)
tensor(1260)
tensor(1280)
tensor(1300)
tensor(1320)
tensor(1340)
tensor(1360)
tensor(1380)
tensor(1400)
tensor(1420)
tensor(1440)
tensor(1460)
tensor(1480)
tensor(1500)
tensor(1520)
tensor(1540)
tensor(1560)
tensor(1580)
tensor(1600)
tensor(1620)


[tensor([ 0., 20.]),
 tensor([ 0., 40.]),
 tensor([ 0., 60.]),
 tensor([ 0., 80.]),
 tensor([  0., 100.]),
 tensor([  0., 120.]),
 tensor([  0., 140.]),
 tensor([  0., 160.]),
 tensor([  0., 180.]),
 tensor([  0., 200.]),
 tensor([  0., 220.]),
 tensor([  0., 240.]),
 tensor([  0., 260.]),
 tensor([  0., 280.]),
 tensor([  0., 300.]),
 tensor([  0., 320.]),
 tensor([  0., 340.]),
 tensor([  0., 360.]),
 tensor([  0., 380.]),
 tensor([  0., 400.]),
 tensor([  0., 420.]),
 tensor([  0., 440.]),
 tensor([  0., 460.]),
 tensor([  0., 480.]),
 tensor([  0., 500.]),
 tensor([  0., 520.]),
 tensor([  0., 540.]),
 tensor([  0., 560.]),
 tensor([  0., 580.]),
 tensor([  0., 600.]),
 tensor([  0., 620.]),
 tensor([  0., 640.]),
 tensor([  0., 660.]),
 tensor([  0., 680.]),
 tensor([  0., 700.]),
 tensor([  0., 720.]),
 tensor([  0., 740.]),
 tensor([  0., 760.]),
 tensor([  0., 780.]),
 tensor([  0., 800.]),
 tensor([  0., 820.]),
 tensor([  0., 840.]),
 tensor([  0., 860.]),
 tensor([  0., 880.